// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGWtI2mst4_QXrDRJosQwjW3VH1tZ3acE',
    appId: '1:721225895024:web:79e39109f5e1cfbf68f8b5',
    messagingSenderId: '721225895024',
    projectId: 'chat-app-e393f',
    authDomain: 'chat-app-e393f.firebaseapp.com',
    storageBucket: 'chat-app-e393f.firebasestorage.app',
    measurementId: 'G-V6BY5PZEZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXxPXu-HWpJiCVd6I_PCS57A_dODsIxEo',
    appId: '1:721225895024:android:bcd3f836b3a584ff68f8b5',
    messagingSenderId: '721225895024',
    projectId: 'chat-app-e393f',
    storageBucket: 'chat-app-e393f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmaSNIhOswDDB_2GDV1kPeDI58QHP-SZA',
    appId: '1:721225895024:ios:d18f3dca36c4493868f8b5',
    messagingSenderId: '721225895024',
    projectId: 'chat-app-e393f',
    storageBucket: 'chat-app-e393f.firebasestorage.app',
    iosClientId: '721225895024-ujvd9tj90ljleosd7kmplugfil5l96uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmaSNIhOswDDB_2GDV1kPeDI58QHP-SZA',
    appId: '1:721225895024:ios:d18f3dca36c4493868f8b5',
    messagingSenderId: '721225895024',
    projectId: 'chat-app-e393f',
    storageBucket: 'chat-app-e393f.firebasestorage.app',
    iosClientId: '721225895024-ujvd9tj90ljleosd7kmplugfil5l96uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGWtI2mst4_QXrDRJosQwjW3VH1tZ3acE',
    appId: '1:721225895024:web:e11d841ce8f913d468f8b5',
    messagingSenderId: '721225895024',
    projectId: 'chat-app-e393f',
    authDomain: 'chat-app-e393f.firebaseapp.com',
    storageBucket: 'chat-app-e393f.firebasestorage.app',
    measurementId: 'G-H1SSZJPCXM',
  );
}
